twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        logo_url: '//placehold.it/200x200&text=Logo'
        logo_alt: 'Logo'
        site_name: 'Site name'
        site_description: 'Lead text description'