version: '3'

services:
  mariadb:
    image: itkdev/mariadb:latest
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryptionn.

  phpfpm:
    image: itkdev/php7.2-fpm:latest
    environment:
      - PHP_XDEBUG=${PHP_XDEBUG:-0}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-0.0.0.0}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      # - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_PROJECT_NAME}.local.computer
    depends_on:
      - mariadb
    volumes:
      - .:/app:delegated
      - drush-cache:/root/.drush

  nginx:
    image: nginx:latest
    depends_on:
      - phpfpm
    ports:
      - '8880:80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - 'traefik.http.routers.frontend.rule=Host(`${COMPOSE_PROJECT_NAME}.local.computer`)'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025'
      - '8885:8025'

# Drush cache volume to persist cache between runs.
volumes:
  drush-cache:
